alias gp='git pull'
alias ga='git add'
alias gb='git branch'
alias gbb='git blame'
alias gch='git checkout'
alias gom='git checkout master'
alias gc='git commit'
alias gcma='git commit -asm'
alias gcam='git commit -asm'
alias gs='git status'
alias gff='git diff -w HEAD^'
alias gf='git diff -w'
alias gfw='git diff -w --word-diff-regex=[^[:space:]]'
alias gfc='git diff -w --cached'
alias gfm='git diff -w master'
